name: phone_numbers_parser
description: Dart library for parsing phone numbers. Inspired by Google's libphonenumber and PhoneNumberKit for ios.
version: 8.1.0
homepage: https://github.com/cedvdb/phone_number_parser

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  meta: ^1.8.0

dev_dependencies:
  xml: ^6.3.0
  lints: ^2.0.1
  test: ^1.21.4
